apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: innowise
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: payment-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: SPRING_PROFILES_ACTIVE
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: SERVER_PORT
            - name: MONGODB_URI
              valueFrom:
                configMapKeyRef:
                  name: payment-service-config
                  key: MONGODB_URI
            - name: RANDOMORG_API_URL
              valueFrom:
                configMapKeyRef:
                  name: payment-service-config
                  key: RANDOMORG_API_URL
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: payment-service-config
                  key: KAFKA_BOOTSTRAP_SERVERS
            - name: KAFKA_TOPIC_ORDER_EVENTS
              valueFrom:
                configMapKeyRef:
                  name: payment-service-config
                  key: KAFKA_TOPIC_ORDER_EVENTS
            - name: KAFKA_TOPIC_PAYMENT_EVENTS
              valueFrom:
                configMapKeyRef:
                  name: payment-service-config
                  key: KAFKA_TOPIC_PAYMENT_EVENTS
            - name: KAFKA_CONSUMER_GROUP_ID
              valueFrom:
                configMapKeyRef:
                  name: payment-service-config
                  key: KAFKA_CONSUMER_GROUP_ID
            - name: SERVICE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: SERVICE_API_KEY
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 90
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: innowise
spec:
  type: ClusterIP
  selector:
    app: payment-service
  ports:
    - port: 8080
      targetPort: 8080

